package domain

import "fmt"

// EvidenceOrigin identifies who or what supplied an evidence record.
type EvidenceOrigin string

const (
	// OriginAnalyzer was generated by an analysis producer.
	OriginAnalyzer EvidenceOrigin = "analyzer"
	// OriginImport was imported from an external source.
	OriginImport EvidenceOrigin = "import"
	// OriginHuman was supplied by a person.
	OriginHuman EvidenceOrigin = "human"
)

// EvidenceResolution records the current disposition of evidence.
type EvidenceResolution string

const (
	// ResolutionUnresolved has not been decided.
	ResolutionUnresolved EvidenceResolution = "unresolved"
	// ResolutionConfirmed was corroborated.
	ResolutionConfirmed EvidenceResolution = "confirmed"
	// ResolutionRejected was determined to be invalid.
	ResolutionRejected EvidenceResolution = "rejected"
	// ResolutionFixed describes an issue corrected after the evidence arose.
	ResolutionFixed EvidenceResolution = "fixed"
)

// EvidenceAssertion states whether the recorded claim was observed or derived.
type EvidenceAssertion string

const (
	// AssertionObserved comes directly from a producer observation.
	AssertionObserved EvidenceAssertion = "observed"
	// AssertionInferred was derived from available evidence.
	AssertionInferred EvidenceAssertion = "inferred"
	// AssertionReported records a submitted claim.
	AssertionReported EvidenceAssertion = "reported"
)

// PositionEncoding defines units used by source positions.
type PositionEncoding string

const (
	// EncodingUTF8 counts UTF-8 code units.
	EncodingUTF8 PositionEncoding = "utf-8"
	// EncodingUTF16 counts UTF-16 code units.
	EncodingUTF16 PositionEncoding = "utf-16"
)

// Position is zero-based. Character counts code units in SourceRange.Encoding.
type Position struct {
	// Line is a zero-based source line index.
	Line int `json:"line"`
	// Character is a zero-based code-unit index in the line.
	Character int `json:"character"`
}

// SourceRange is half-open: Start is included and End is excluded.
type SourceRange struct {
	// RepositoryID identifies the repository containing Path.
	RepositoryID RepositoryID `json:"repositoryId"`
	// Path is a portable repository-relative source path.
	Path string `json:"path"`
	// Encoding specifies units for Start and End character positions.
	Encoding PositionEncoding `json:"encoding"`
	// Start is the included range boundary.
	Start Position `json:"start"`
	// End is the excluded range boundary.
	End Position `json:"end"`
}

// Validate checks repository identity, portable path, supported encoding, and order.
func (r SourceRange) Validate() error {
	if r.RepositoryID == "" {
		return fmt.Errorf("source range requires repository identity")
	}
	if err := ValidateRelativePath(r.Path, false); err != nil {
		return err
	}
	if r.Encoding != EncodingUTF8 && r.Encoding != EncodingUTF16 {
		return fmt.Errorf("unsupported position encoding %q", r.Encoding)
	}
	if r.Start.Line < 0 || r.Start.Character < 0 || r.End.Line < 0 || r.End.Character < 0 || r.End.Line < r.Start.Line || (r.End.Line == r.Start.Line && r.End.Character < r.Start.Character) {
		return fmt.Errorf("invalid half-open source range")
	}
	return nil
}

// Origin, resolution, and assertion are orthogonal; e.g. a human report may be
// rejected without altering its origin or what was originally asserted.
type Evidence struct {
	// ID uniquely identifies this evidence record.
	ID string `json:"id"`
	// ViewID pins evidence to an immutable analysis view.
	ViewID ViewID `json:"viewId"`
	// Origin identifies the contributing source.
	Origin EvidenceOrigin `json:"origin"`
	// Resolution records its current disposition.
	Resolution EvidenceResolution `json:"resolution"`
	// Assertion records how the claim was made.
	Assertion EvidenceAssertion `json:"assertion"`
	// Range locates supporting source evidence.
	Range SourceRange `json:"range"`
	// Summary is a human-readable concise claim.
	Summary string `json:"summary"`
}

// Validate checks required identity, enum values, and the supporting source span.
func (e Evidence) Validate() error {
	if e.ID == "" || e.ViewID == "" {
		return fmt.Errorf("evidence requires identity and view")
	}
	if e.Origin != OriginAnalyzer && e.Origin != OriginImport && e.Origin != OriginHuman {
		return fmt.Errorf("invalid origin")
	}
	if e.Resolution != ResolutionUnresolved && e.Resolution != ResolutionConfirmed && e.Resolution != ResolutionRejected && e.Resolution != ResolutionFixed {
		return fmt.Errorf("invalid resolution")
	}
	if e.Assertion != AssertionObserved && e.Assertion != AssertionInferred && e.Assertion != AssertionReported {
		return fmt.Errorf("invalid assertion")
	}
	return e.Range.Validate()
}
